# Generated by Django 5.2.1 on 2025-05-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='initial_deposite_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
